version: 2.1

orbs:
  wp-svn: studiopress/wp-svn@0.2

executors:
  php_node:
    docker:
      - image: cimg/php:7.3-node

jobs:
  checks:
    executor: php_node
    steps:
      - checkout
      - run: composer install && composer phpcs

workflows:
  test-deploy:
    jobs:
      - checks
      - approval-for-deploy-tested-up-to-bump:
          requires:
            - checks
          type: approval
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /^bump-tested-up-to.*/
      - wp-svn/deploy-tested-up-to-bump:
          context: genesis-svn
          requires:
            - approval-for-deploy-tested-up-to-bump
      - wp-svn/deploy:
          context: genesis-svn
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
          requires:
            - checks
